[package]
name = "sample-extension"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
serde = "1.0.227"
serde_json = "1.0.145"
thiserror = "2.0.16"
url = "2.5.7"
wit-bindgen = "0.46.0"
